volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: 25andrey25/departments_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend
  gateway:
    image: 25andrey25/departments_gateway
    ports:
      - 8000:80 
    depends_on:
      - backend
    volumes:
      - static:/staticfiles