# Generated by Django 5.1.1 on 2026-05-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подразделения', max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('parent', models.ForeignKey(blank=True, help_text='Подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'Подразделения',
                'unique_together': {('name', 'parent_id')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Имя сотрудника', max_length=200, verbose_name='Имя')),
                ('position', models.CharField(help_text='Должность сотрудника', max_length=200, verbose_name='Должность')),
                ('hired_at', models.DateField(blank=True, help_text='Нанят', null=True, verbose_name='Нанят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('department', models.ForeignKey(help_text='Подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
